Move drag and drop js into data section so that it will be available …
sorryforthecommit/WWW-WebKit2 pull request #58
Opened 2020-03-23 14:57 UTC by pvoglhofer

…when installed as module

2020-03-27 07:05 UTC, pvoglhofer commented
I've moved the drag and drop simulator into its own file, should be a bit cleaner now.

2020-03-27 07:18 UTC, niner requested changes

2020-03-27 07:18 UTC, niner commented on lib/WWW/WebKit2/MouseInput.pm
> +__DATA__
This can go now I guess?

2020-03-27 07:42 UTC, pvoglhofer commented on lib/WWW/WebKit2/MouseInput.pm
> +__DATA__
Indeed. Fixed.

2020-03-30 09:07 UTC, muddasheep approved these changes

2020-03-30 14:56 UTC, niner approved these changes

2020-03-31 13:46 UTC, merged